# Generated by Django 2.0.4 on 2018-04-12 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maturity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assessment Date', models.DateTimeField()),
                ('user_name', models.CharField(max_length=120)),
                ('user_email', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=-1)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maturity.Assessment')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maturity.Criteria')),
            ],
        ),
    ]
