# Generated by Django 2.0.4 on 2018-04-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturity', '0002_assessment_assessmentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentanswer',
            name='value',
            field=models.IntegerField(),
        ),
    ]
