# Generated by Django 2.0.4 on 2018-04-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maturity', '0004_auto_20180412_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='current_assessment_item',
            field=models.IntegerField(default=-1),
        ),
    ]
